name: PyRight

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run PyRight
      uses: jakebailey/pyright-action@v1
      with:
        python-version: 3.7
